name: Generate and push sandboxes

on:
  schedule:
    - cron: '2 2 */1 * *'
  workflow_dispatch:
  # To test fixes on push rather than wait for the scheduling, do the following:
  # 1. Uncomment the lines below and add your branch.
  # push:
  #   branches:
  #     - <your-branch-name>
  # 2. change the "ref" value to <your-branch-name> in the actions/checkout step below.
  # 3. 👉 DON'T FORGET TO UNDO THE VALUES BACK BEFORE YOU MERGE YOUR CHANGES!

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      CLEANUP_SANDBOX_NODE_MODULES: true
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16
          - 18
        branch:
          - main
          - next
        include:
          - node_version: 16
            # space-delimited list of templates
            exclude: 'angular-cli/prerelease'
          - node_version: 18
            # space-delimited list of templates
            templates: 'angular-cli/prerelease'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Setup git user
        run: |
          git config --global user.name "Storybook Bot"
          git config --global user.email "bot@storybook.js.org"

      - name: Install dependencies
        run: node ./scripts/check-dependencies.js

      - name: Compile Storybook libraries
        run: yarn task --task compile --start-from=auto --no-link

      - name: Publishing to local registry
        run: yarn local-registry --publish
        working-directory: ./code

      - name: Running local registry
        run: yarn local-registry --open &
        working-directory: ./code

      - name: Wait for registry
        run: yarn wait-on http://localhost:6001
        working-directory: ./code

      - name: Generate
        run: yarn generate-sandboxes --local-registry --templates ${{matrix.templates}} --exclude ${{matrix.exclude}}
        working-directory: ./code

      - name: Publish
        run: yarn publish-sandboxes --remote=https://storybook-bot:${{ secrets.PAT_STORYBOOK_BOT}}@github.com/storybookjs/sandboxes.git --push --branch=${{ matrix.branch }}
        working-directory: ./code

      - name: The job has failed
        if: ${{ failure() || cancelled() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_MONITORING_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The generation of sandboxes with Node version **${{ matrix.node_version }}** in the **${{ matrix.branch }}** branch has failed. [View Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
